# Узел 1 кластера NATS. Отличия от соседей: server_name и список routes.

server_name: n1
port: 4222
http_port: 8222

jetstream {
  store_dir: /data/jetstream
}

cluster {
  name: nats-demo-cluster
  port: 6222
  routes: [
    nats://n2:6222
    nats://n3:6222
  ]
}

authorization {
  users: [
    { user: demo, password: secret }
  ]
}
