set -g mouse on
set -g pane-border-status top
set -g pane-border-format " #{pane_index}: #{pane_title} "
set -g status-style "bg=colour24,fg=white"
set -g status-left " NATS demo "
set -g status-right ""
set -g history-limit 5000
